#!/bin/sh
echo $1
echo $2
cd $2
if [ "$1" = "-lower" ];then
	for var in `ls $2`; do 
		tmp=`echo "$var" | awk -F '.' '{print $1}'`;
		exp=`echo "$var" | awk -F '.' '{print $2}'`;
		lower=`echo "$tmp" |tr A-Z a-z`;
		mv  "$var" `echo "${lower}.${exp}"`; 
	done
elif [ "$1" = "-upper" ];then
	for var in `ls $2`; do
                tmp=`echo "$var" | awk -F '.' '{print $1}'`;
                exp=`echo "$var" | awk -F '.' '{print $2}'`;
                upper=`echo "$tmp" |tr a-z A-Z`;
                mv  "$var" `echo "${upper}.${exp}"`;
        done
fi
